/** Locale-owned labels for the execution inspector. */
const zh = {
  newAnalysis: '新建分析',
  sessions: '分析记录',
  newSession: '新的分析',
  session: '分析',
  noSessions: '暂无分析记录',
  deleteAnalysis: '删除分析记录',
  confirmDeleteAnalysis: '确认删除',
  deleteAnalysisNotice: '从列表移除，保留历史日志和报告文件',
  stopBeforeDelete: '请先停止分析，再删除记录',
  deleteAnalysisFailed: '删除失败，记录已保留',
  analysisDeleted: '分析记录已删除',
  historyVisibilityFailed: '无法读取记录状态，请刷新重试',
  workspace: '分析工作台',
  sources: '数据源',
  sourceName: '名称',
  sourceType: '类型',
  noSources: '暂无数据源',
  chooseSource: '选择数据源',
  noSource: '未选择数据源',
  currentSource: '当前数据源',
  recentActivity: '最近活动',
  questionPlaceholder: '描述分析需求、时间范围和报告要求',
  send: '发送',
  stop: '停止',
  now: '刚刚',
  minutesAgo: '分钟前',
  hoursAgo: '小时前',
  daysAgo: '天前',
  suggestions: '分析任务',
  overviewTask: '检查表结构、字段与关联',
  trendTask: '按时间汇总记录数并分析变化',
  reportTask: '生成包含结论、方法和证据的分析报告',
  reasoning: '模型输出记录',
  analyzing: '正在分析',
  table: '表格',
  chart: '图表',
  rows: '行',
  previewOnly: '预览',
  query: '查询数据',
  readDocument: '阅读资料',
  discover: '发现数据源',
  searchDocuments: '检索资料',
  importDataset: '导入数据',
  analyze: '计算分析',
  renderChart: '生成图表',
  report: '生成报告',
  reportFormat: '报告格式',
  reportRequestFailed: '报告请求未发送，请重试',
  reportRequest: '请将第 {turn} 轮的最终分析生成 {format} 报告。保留结论、方法、业务口径和限制，复用该轮已验证的数据；结果缺失或数据源已改变时先重新核验。将完整 Markdown 内容交给 report 生成可下载文件，不在聊天中重复整篇报告。',
  submit: '最终结果',
  benchmark: '提交评测 SQL',
  chartEmpty: '没有可绘图的数值列',
  failedTool: '执行失败',
  commandRunning: '执行中',
  transcriptDisabled: '聊天渲染已关闭',
  clarification: '待确认问题',
  customAnswer: '补充回答',
  answer: '提交回答',
  execution: '执行过程',
  request: '模型请求',
  step: '步骤',
  attempt: '尝试',
  turn: '轮次',
  tools: '工具',
  system: '提示词',
  context: '上下文',
  declarations: '可用工具',
  toolPurposes: '工具用途',
  toolPurpose: '作用',
  originalDefinitions: '原始定义',
  purposeRead: '按路径读取文本文件，可按行分页阅读资料或 SQL 结果',
  purposeGrep: '检索文件内容',
  purposeFind: '按文件名模式查找文件',
  purposeLs: '列出目录的直接子项',
  purposeSql: '执行只读 SQL，返回完整结果路径、行数与预览',
  purposeReport: '提交完整 Markdown 内容，生成 Markdown、HTML 或 PDF 报告；修改时保存新版本',
  purposeBenchmark: '提交最终 SQL 和可选答案，供 BIRD／Spider 评测读取',
  purposeListSources: '发现当前分析生效的数据源，以及 Schema、业务资料和索引 MD 的版本引用',
  purposeListDatabases: '兼容旧调用的数据源发现入口，作用与 list_sources 相同',
  purposeSearchDocuments: '检索 Schema、业务口径、技能、模板和结果摘要，返回可阅读的 MD 引用',
  purposeReadDocument: '按文档 ID 和版本分页阅读 MD，保留实际读取的内容与版本',
  purposeImportDataset: '导入会话工作区内的 CSV、Excel 或 Parquet，生成工作表与 Schema MD，保留原文件',
  purposeQueryDatabase: '在生效库表范围执行只读 SQL，保存完整受限结果，返回结果标识和预览',
  purposeAnalyzeData: '对已保存的完整结果进行分组聚合、排序、去空值、去重、关联或期间对比，不执行任意代码',
  purposeRenderChart: '使用已保存的结果和指定字段生成可下载的 SVG 柱状图',
  purposeGenerateReport: '以 Markdown 为内容源，绑定数据结果与图表，生成 Markdown、HTML 或 PDF 报告',
  purposeSubmitAnalysis: '记录最终答案、SQL、结果引用和交付文件，供产品与评测读取；不代替计算核验',
  purposeAskUserQuestion: '向用户澄清歧义、缺失条件或待确认口径，等待选择或补充回答',
  purposePresent: '将已经存在的文件声明为用户可获取的交付物，本身不生成文件',
  purposeSubagent: '将独立子任务交给子 Agent 执行并获取结果',
  purposeWorkflow: '通过 JavaScript 工作流组织阶段与子 Agent，支持并发任务和结构化结果',
  info: '请求信息',
  raw: '原文',
  output: '模型输出',
  retry: '重试等待',
  missing: '该历史记录没有实际请求定位信息',
  empty: '暂无执行记录',
  loading: '加载中',
  next: '下一页',
  previous: '上一页',
  close: '关闭',
  expand: '宽屏详情',
  showComplete: '展开全文',
  downloadComplete: '下载完整内容',
  completeContent: '完整内容',
  characters: '字符',
  search: '搜索执行记录',
  all: '全部状态',
  running: '运行中',
  completed: '已完成',
  failed: '失败',
  cancelled: '已取消',
  unavailable: '不可用',
  input: '输入',
  outputTokens: '输出',
  cacheRead: '缓存读取',
  cacheWrite: '缓存写入',
  workflow: '工作流',
  args: '调用参数',
  result: '完整工具结果',
  exportMd: '导出 trace.md',
  exportJson: '导出 trajectory.json',
  child: '子 Agent',
  phase: '阶段',
  finish: '结束原因',
  error: '错误',
  preview: '预览报告',
  notLoggedIn: '未登录：请使用 dsh 启动时提供的地址',
  invalidRpcResponse: 'RPC 响应格式错误',
  rpcFailed: 'RPC 失败',
  historyFailed: '读取历史失败',
  streamFailed: '日志流错误',
  createSessionFailed: '创建会话失败',
  createSessionFirst: '请先新建一个分析会话',
  sendFailed: '发送失败',
  chooseSourceFailed: '选择数据源失败',
  manageSources: '数据源管理',
  backAnalysis: '返回分析',
  applyScope: '应用数据库选择',
  enabledDatabase: '生效数据库',
  databaseTables: '数据表',
  allTablesEnabled: '生效数据库的所有表均可查询',
  connections: '连接',
  addConnection: '连接 MySQL',
  connectionLabel: '连接名称',
  host: '主机',
  port: '端口',
  username: '用户名',
  password: '密码',
  credentialReference: '凭据环境变量（可选）',
  tls: 'TLS 证书校验',
  testConnection: '测试连接',
  saveConnection: '保存连接',
  accessibleDatabases: '可连接数据库',
  createDatabase: '新建数据库',
  newDatabaseName: '新数据库名称',
  removeConnection: '移除连接配置',
  refreshSchema: '刷新表列表',
  filterTables: '筛选表',
  fields: '字段',
  noTables: '暂无表',
  defaultDatabase: '默认查询库',
  downloadSchema: '下载 schema.md',
  uploadSchema: '上传 Schema MD',
  businessTab: '业务口径.md',
  schemaLibrary: 'Schema 知识库',
  businessLibrary: '业务知识库',
  addDocuments: '添加 MD',
  filterDocuments: '搜索文档',
  noDocuments: '暂无文档',
  documentConfigured: '项目资料',
  documentUploaded: '用户资料',
  enableDocument: '生效',
  replaceDocument: '替换文档',
  removeDocument: '移除文档',
  confirmRemoveDocument: '确认移除',
  documentSaved: '知识库已更新',
  documentRemoved: '文档已移除，历史分析证据保留',
  documentLoadFailed: '知识库加载失败',
  selectDocument: '选择文档',
  downloadDocument: '下载文档',
  cancelOperation: '取消操作',
  downloadBusiness: '下载业务口径.md',
  uploadBusiness: '上传业务口径 MD',
  businessUploaded: '业务口径已保存',
  sourceOperationFailed: '数据源操作失败',
  connectionTested: '连接成功，请选择要保存的数据库',
  connectionSaved: '连接已保存',
  connectionRemoved: '连接配置已移除，数据库未删除',
  databaseCreated: '空数据库已创建',
  schemaUploaded: 'Schema MD 已上传，实际字段结构保持不变',
  scopeSaved: '数据库选择已应用到当前分析',
  scopeNotSaved: '库表范围未保存，请停止分析后重试',
  stopBeforeScope: '请停止当前分析后修改生效库表',
  manageModels: '模型与 API',
  currentModel: '当前模型',
  lastModel: '最近使用',
  nextModel: '下次请求',
  modelDefault: '默认模型',
  modelUnavailable: '模型目录不可用',
  modelOperationFailed: '模型操作失败',
  provider: '供应商',
  addModelApi: '接入模型 API',
  providerRoute: '供应商标识',
  providerName: '显示名称',
  endpoint: 'Base URL',
  protocol: 'API 协议',
  apiKey: 'API Key',
  keyConfigured: '凭据已配置',
  keyNotConfigured: '未配置凭据',
  keyReadOnly: '凭据来自只读来源',
  keyOptional: '留空保留原凭据',
  keyOptionalCreate: '可留空',
  apiModels: '模型列表',
  modelId: '模型 ID',
  modelName: '模型名称',
  contextWindow: '上下文上限',
  maxTokens: '输出上限',
  imageInput: '图像输入',
  reasoningEffort: '推理强度',
  addModel: '添加模型',
  removeModel: '移除模型',
  discoverModels: '发现模型',
  discoveryCandidates: '可添加模型',
  discoveryEmpty: '服务端未返回模型，可手动添加',
  saveModelApi: '保存配置',
  retryModelKey: '重试保存凭据',
  modelApiSaved: '模型配置已保存',
  modelKeyPending: '配置已保存，但凭据未保存',
  modelApiRemoved: '模型配置已移除，凭据保持不变',
  removeModelApi: '移除接入配置',
  confirmRemoveApi: '确认移除配置',
  cancelEdit: '取消',
  settingsReadOnly: '此运行环境不允许修改模型配置',
  modelApiUnavailable: '未加载自定义 API 适配器',
  settingsConflict: '配置已被其他窗口修改，请重新打开编辑器',
  routeInvalid: '供应商标识须以小写字母开头，仅含小写字母、数字和连字符',
  routeTaken: '供应商标识已存在',
  endpointInvalid: '请输入不含用户名和密码的 HTTP 或 HTTPS 地址',
  protocolRequired: '请选择 API 协议',
  modelRequired: '至少添加一个模型',
  modelIdsInvalid: '模型 ID 不能为空或重复',
  capacityInvalid: 'Token 上限须为正整数，输出不能超过上下文上限',
  keyInvalid: 'API Key 不能含空格或非 ASCII 字符',
  configuredModels: '已配置模型',
  refreshModels: '刷新模型目录',
  inheritedProvider: '运行配置',
  customProvider: '自定义接入',
} as const
const en: Record<keyof typeof zh, string> = {
  newAnalysis: 'New analysis',
  sessions: 'Analyses',
  newSession: 'New analysis',
  session: 'Analysis',
  noSessions: 'No analyses',
  deleteAnalysis: 'Delete analysis record',
  confirmDeleteAnalysis: 'Confirm deletion',
  deleteAnalysisNotice: 'Remove from the list; retain historical logs and report files',
  stopBeforeDelete: 'Stop the analysis before deleting its record',
  deleteAnalysisFailed: 'Deletion failed; the record is retained',
  analysisDeleted: 'Analysis record deleted',
  historyVisibilityFailed: 'Record status unavailable; refresh to retry',
  workspace: 'Analysis workspace',
  sources: 'Data sources',
  sourceName: 'Name',
  sourceType: 'Type',
  noSources: 'No data sources',
  chooseSource: 'Select source',
  noSource: 'No source selected',
  currentSource: 'Current source',
  recentActivity: 'Last activity',
  questionPlaceholder: 'Describe your analysis, time range, and report requirements',
  send: 'Send',
  stop: 'Stop',
  now: 'Just now',
  minutesAgo: 'min ago',
  hoursAgo: 'hr ago',
  daysAgo: 'days ago',
  suggestions: 'Analysis tasks',
  overviewTask: 'Inspect tables, fields, and relationships',
  trendTask: 'Group record counts by time and analyze changes',
  reportTask: 'Generate a report with conclusions, methods, and evidence',
  reasoning: 'Model output record',
  analyzing: 'Analyzing',
  table: 'Table',
  chart: 'Chart',
  rows: 'rows',
  previewOnly: 'Preview',
  query: 'Query data',
  readDocument: 'Read document',
  discover: 'Discover sources',
  searchDocuments: 'Search documents',
  importDataset: 'Import dataset',
  analyze: 'Analyze data',
  renderChart: 'Render chart',
  report: 'Generate report',
  reportFormat: 'Report format',
  reportRequestFailed: 'Report request was not sent; try again',
  reportRequest: 'Generate a {format} report from the final analysis in turn {turn}. Keep conclusions, methods, business definitions and limitations, and reuse its verified data. Recheck missing results or a changed source. Send complete Markdown content to report for downloadable files, without repeating the entire report in chat.',
  submit: 'Final result',
  benchmark: 'Submit benchmark SQL',
  chartEmpty: 'No numeric fields to chart',
  failedTool: 'Execution failed',
  commandRunning: 'Running',
  transcriptDisabled: 'Transcript rendering disabled',
  clarification: 'Clarification',
  customAnswer: 'Your answer',
  answer: 'Submit answer',
  execution: 'Execution',
  request: 'Model request',
  step: 'Step',
  attempt: 'Attempt',
  turn: 'Turn',
  tools: 'Tools',
  system: 'System prompt',
  context: 'Context',
  declarations: 'Available tools',
  toolPurposes: 'Tool purposes',
  toolPurpose: 'Purpose',
  originalDefinitions: 'Original definitions',
  purposeRead: 'Read a text file by path, with optional line windows',
  purposeGrep: 'Search file contents',
  purposeFind: 'Find files by name pattern',
  purposeLs: 'List immediate directory entries',
  purposeSql: 'Run read-only SQL and return the complete file, row count and preview',
  purposeReport: 'Generate Markdown, HTML or PDF from complete Markdown content; revisions save new files',
  purposeBenchmark: 'Submit the final SQL and optional answer for BIRD/Spider evaluation',
  purposeListSources: 'Discover enabled sources and versioned Schema, business knowledge and index Markdown references',
  purposeListDatabases: 'Legacy source discovery alias with the same role as list_sources',
  purposeSearchDocuments: 'Search Schema, business definitions, skills, templates and result summaries for readable Markdown references',
  purposeReadDocument: 'Read Markdown by document ID and version, page by page, retaining the content and version actually read',
  purposeImportDataset: 'Import CSV, Excel or Parquet from the session workspace, generate worksheet and Schema Markdown, and retain original files',
  purposeQueryDatabase: 'Run read-only SQL within the enabled source/table scope; save complete bounded results and return their IDs and previews',
  purposeAnalyzeData: 'Group, aggregate, sort, drop nulls, deduplicate, join or compare periods over complete saved results without arbitrary code execution',
  purposeRenderChart: 'Generate a downloadable SVG bar chart from a saved result and selected fields',
  purposeGenerateReport: 'Generate Markdown, HTML or PDF reports from Markdown content bound to data results and charts',
  purposeSubmitAnalysis: 'Record the final answer, SQL, result references and delivered files for product and evaluation consumers; does not replace verification',
  purposeAskUserQuestion: 'Clarify ambiguity, missing conditions or business definitions and wait for a choice or free-text answer',
  purposePresent: 'Declare existing files as user deliverables; does not create files',
  purposeSubagent: 'Delegate a focused task to a child Agent and obtain its result',
  purposeWorkflow: 'Organize phases and child Agents through JavaScript workflows, with concurrent tasks and structured results',
  info: 'Request info',
  raw: 'Original',
  output: 'Model output',
  retry: 'Retry wait',
  missing: 'Actual request details are unavailable for this historical record',
  empty: 'No execution records',
  loading: 'Loading',
  next: 'Next page',
  previous: 'Previous page',
  close: 'Close',
  expand: 'Wide details',
  showComplete: 'Show complete content',
  downloadComplete: 'Download complete content',
  completeContent: 'Complete content',
  characters: 'Characters',
  search: 'Search execution',
  all: 'All states',
  running: 'Running',
  completed: 'Completed',
  failed: 'Failed',
  cancelled: 'Cancelled',
  unavailable: 'Unavailable',
  input: 'Input',
  outputTokens: 'Output',
  cacheRead: 'Cache read',
  cacheWrite: 'Cache write',
  workflow: 'Workflow',
  args: 'Arguments',
  result: 'Complete tool observation',
  exportMd: 'Export trace.md',
  exportJson: 'Export trajectory.json',
  child: 'Child Agent',
  phase: 'Phase',
  finish: 'Finish reason',
  error: 'Error',
  preview: 'Preview report',
  notLoggedIn: 'Not signed in: use the address provided by dsh at startup',
  invalidRpcResponse: 'Invalid RPC response',
  rpcFailed: 'RPC failed',
  historyFailed: 'Failed to read history',
  streamFailed: 'Event stream failed',
  createSessionFailed: 'Failed to create session',
  createSessionFirst: 'Create an analysis session first',
  sendFailed: 'Failed to send',
  chooseSourceFailed: 'Failed to select source',
  manageSources: 'Data sources',
  backAnalysis: 'Back to analysis',
  applyScope: 'Apply database selection',
  enabledDatabase: 'Enabled database',
  databaseTables: 'Tables',
  allTablesEnabled: 'All tables in enabled databases are available',
  connections: 'Connections',
  addConnection: 'Connect MySQL',
  connectionLabel: 'Connection name',
  host: 'Host',
  port: 'Port',
  username: 'Username',
  password: 'Password',
  credentialReference: 'Credential environment variable (optional)',
  tls: 'Verify TLS certificate',
  testConnection: 'Test connection',
  saveConnection: 'Save connection',
  accessibleDatabases: 'Accessible databases',
  createDatabase: 'Create database',
  newDatabaseName: 'New database name',
  removeConnection: 'Remove connection configuration',
  refreshSchema: 'Refresh table list',
  filterTables: 'Filter tables',
  fields: 'fields',
  noTables: 'No tables',
  defaultDatabase: 'Default query database',
  downloadSchema: 'Download schema.md',
  uploadSchema: 'Upload schema MD',
  businessTab: 'business.md',
  schemaLibrary: 'Schema knowledge',
  businessLibrary: 'Business knowledge',
  addDocuments: 'Add MD',
  filterDocuments: 'Search documents',
  noDocuments: 'No documents',
  documentConfigured: 'Project reference',
  documentUploaded: 'User reference',
  enableDocument: 'Enabled',
  replaceDocument: 'Replace document',
  removeDocument: 'Remove document',
  confirmRemoveDocument: 'Confirm removal',
  documentSaved: 'Knowledge library updated',
  documentRemoved: 'Document removed; historical evidence retained',
  documentLoadFailed: 'Could not load knowledge library',
  selectDocument: 'Select a document',
  downloadDocument: 'Download document',
  cancelOperation: 'Cancel operation',
  downloadBusiness: 'Download business.md',
  uploadBusiness: 'Upload business knowledge MD',
  businessUploaded: 'Business knowledge saved',
  sourceOperationFailed: 'Data source operation failed',
  connectionTested: 'Connected. Select databases to save',
  connectionSaved: 'Connection saved',
  connectionRemoved: 'Connection removed; databases were not deleted',
  databaseCreated: 'Empty database created',
  schemaUploaded: 'Schema MD uploaded; actual fields remain unchanged',
  scopeSaved: 'Database selection applied to this analysis',
  scopeNotSaved: 'Source scope was not saved; stop the analysis and retry',
  stopBeforeScope: 'Stop the current analysis before changing its data scope',
  manageModels: 'Models & API',
  currentModel: 'Current model',
  lastModel: 'Last used',
  nextModel: 'Next request',
  modelDefault: 'Default model',
  modelUnavailable: 'Model catalog unavailable',
  modelOperationFailed: 'Model operation failed',
  provider: 'Provider',
  addModelApi: 'Connect model API',
  providerRoute: 'Provider ID',
  providerName: 'Display name',
  endpoint: 'Base URL',
  protocol: 'API protocol',
  apiKey: 'API Key',
  keyConfigured: 'Credential configured',
  keyNotConfigured: 'No credential configured',
  keyReadOnly: 'Credential supplied by a read-only source',
  keyOptional: 'Leave blank to keep the existing credential',
  keyOptionalCreate: 'Optional',
  apiModels: 'Models',
  modelId: 'Model ID',
  modelName: 'Model name',
  contextWindow: 'Context limit',
  maxTokens: 'Output limit',
  imageInput: 'Image input',
  reasoningEffort: 'Reasoning effort',
  addModel: 'Add model',
  removeModel: 'Remove model',
  discoverModels: 'Discover models',
  discoveryCandidates: 'Available models',
  discoveryEmpty: 'No models returned; add one manually',
  saveModelApi: 'Save configuration',
  retryModelKey: 'Retry credential save',
  modelApiSaved: 'Model configuration saved',
  modelKeyPending: 'Configuration saved; credential was not saved',
  modelApiRemoved: 'Configuration removed; credentials retained',
  removeModelApi: 'Remove API configuration',
  confirmRemoveApi: 'Confirm removal',
  cancelEdit: 'Cancel',
  settingsReadOnly: 'This runtime does not allow model configuration changes',
  modelApiUnavailable: 'Custom API adapter is not loaded',
  settingsConflict: 'Another window changed this configuration; reopen the editor',
  routeInvalid: 'Provider ID must start with a lowercase letter and contain lowercase letters, digits or hyphens',
  routeTaken: 'Provider ID already exists',
  endpointInvalid: 'Enter an HTTP or HTTPS URL without embedded credentials',
  protocolRequired: 'Choose an API protocol',
  modelRequired: 'Add at least one model',
  modelIdsInvalid: 'Model IDs cannot be empty or repeated',
  capacityInvalid: 'Token limits must be positive integers; output cannot exceed context',
  keyInvalid: 'API Key cannot contain spaces or non-ASCII characters',
  configuredModels: 'Configured models',
  refreshModels: 'Refresh model catalog',
  inheritedProvider: 'Runtime configuration',
  customProvider: 'Custom connection',
}
/** Resolve a typed execution label in the browser's locale. */
export function t(key: keyof typeof zh): string {
  return navigator.language.startsWith('zh') ? zh[key] : en[key]
}
